### ISSUE TITLE
Package cannot be used with Angular

### ISSUE THREAD

**Issue by Aniket-Engg** [AudiusProject/hedgehog#10]
Not able to use this package in Angular because of this : https://github.com/angular/angular-cli/issues/1548
And they explain this here: https://github.com/angular/angular-cli/issues/1548#issuecomment-286151056

Error I am getting is: 
```
ERROR in ./node_modules/@audius/hedgehog/src/authentication.js
Module not found: Error: Can't resolve 'crypto' in '/node_modules/@audius/hedgehog/src'
ERROR in ./node_modules/ethereumjs-wallet/index.js
Module not found: Error: Can't resolve 'crypto' in '/node_modules/ethereumjs-wallet'
ERROR in ./node_modules/hdkey/lib/hdkey.js
Module not found: Error: Can't resolve 'crypto' in '/node_modules/hdkey/lib'
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in '/node_modules/cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'stream' in '/node_modules/hash-base'
ERROR in ./node_modules/keccak/lib/api/keccak.js
Module not found: Error: Can't resolve 'stream' in '/node_modules/keccak/lib/api'
ERROR in ./node_modules/keccak/lib/api/shake.js
Module not found: Error: Can't resolve 'stream' in '/node_modules/keccak/lib/api'
```

**Comment by dmanjunath** [comment]
Thanks for bringing up this issue Aniket. From the attached thread, I'm not sure how much Hedgehog can do to support this intentional limitation in the angular-cli. If you have a solution please submit a PR!

**Comment by Aniket-Engg** [comment]
I either don't see a solution to implement in hedgehog. Probably we can use the substitute of packages which is not supported by angular or can mention a way around in documentation to make it easy for coming developers.

**Comment by dmanjunath** [comment]
I'm not sure this is something we can fix on the hedgehog side if angular is blocking certain packages. I'm going to close this because I'm not sure there's really anything we can do here
