### ISSUE TITLE
process of change password

### ISSUE THREAD

**Issue by Aniket-Engg** [AudiusProject/hedgehog#13]
This can be great if you can add an API to support the change password functionality of already signed up.

Or, it can be explained in the documentation with present feature set.

**Comment by dmanjunath** [comment]
Hi @Aniket-Engg,

The way the module is currently implemented it's not possible to recover the existing password so changing the password won't work. More details are given here https://audiusproject.github.io/hedgehog-docs/#important-lost-passwords.

If you can think of an a mechanism to encrypt the private key client side with a recoverable password strategy please submit a pull request!

**Comment by Aniket-Engg** [comment]
Hello @dmanjunath , the link you mentioned describes that if password is lost, account can not be recovered. I am talking about a case where user knows its previous password and want to set a new password by telling the old one. I thought that this would be possible as in same link documentation says: 

> And since the old password is required to decrypt the entropy and re-encrypt with a new password

which seems a case of changing password. Please correct me if I am still getting it wrong.
