### ISSUE TITLE
[Question] What is the status of this repository?

### ISSUE THREAD

**Issue by SimonLuckenuik** [AudiusProject/hedgehog#29]
Hi,

It seems there was no release in over a year and not much activity in the repo.
Is this library still supported (and just flawless :-)) or does the concept had too many flaws and approach was changed?
Hedgehog approach/UX seems very interesting for consumer level DApps.

Thanks!
Simon

**Comment by dmanjunath** [comment]
Hi @SimonLuckenuik, the library is still supported and is being used. There hasn't been much activity since there haven't been too many changes that have been needed to be made. Thanks for your interest!

**Comment by SimonLuckenuik** [comment]
Thank you for the quick feedback, I will look into it then :-)
