### ISSUE TITLE
How to send an initial recovery email to user with hedgehog?

### ISSUE THREAD

**Issue by amplicity** [AudiusProject/hedgehog#45]
Hey! In the docs I see:

>IMPORTANT: Lost Passwords
If a user loses their password, the account is no longer recoverable. There's no way to reset a password because the entropy is encrypted client side before it's sent to the database. And since the old password is required to decrypt the entropy and re-encrypt with a new password, if the password used to encrypt the entropy has been lost or forgotten, the account is not recoverable.

However, on Audius, I see the ability to recover your password. It appears that Audius sends a recovery email that contains some key to login to the account forever. 

Is this recovery method supported with hedgehog? I'm not seeing how it's possible without knowing the user's password.

**Comment by raymondjacobson** [comment]
Hey @amplicity, great question. Apologies on our end for the late response here. Password recovery can only be triggered client side once the user has re-authenticated (and decrypted the ciphertext). Hope this offers some clarity!

**Comment by raymondjacobson** [comment]
https://github.com/AudiusProject/audius-client/blob/3301e274eaa537f048aecefe85c5618ede9f0e06/packages/web/src/services/AudiusBackend.js#L1793

Here is the reference implementation!
