### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by miguelmota** [AudiusProject/hedgehog#9]
Cool demo! ..but what's preventing a third party library or extension from reading the site's local storage and retrieving the entropy value to derive the hd wallet? trying to see what the benefit of hedgehog is over simply using [truffle-hdwallet-provider](https://github.com/trufflesuite/truffle-hdwallet-provider) by supplying a mnemonic generated by the entropy

**Comment by raymondjacobson** [comment]
Hey there! Thanks for the question. We somewhat have documented this in our docs page
https://audiusproject.github.io/hedgehog-docs/#security-considerations

Using hedgehog definitely comes with tradeoffs. The point of most of our decisions thus far have been to decrease usability friction. We're exploring options regarding sandboxing the entropy, but at the time being unfortunately auditing is important. We're all open to suggestions! Feel free to re-open.

**Comment by superoo7** [comment]
Can consider moving from localstorage to indexed db

https://stackoverflow.com/questions/13453418/is-it-possible-for-a-chrome-extension-to-access-an-indexeddb-database-created-by

**Comment by dmanjunath** [comment]
Thanks for the comment @superoo7. We considered that approach too, but as far as I'm aware, indexed db is open to the same vulnerability as localStorage. While chrome extensions and other domains cannot access indexed db, any javascript imported through the <script> tag could still access the local domain's indexed db and should still be audited.

**Comment by dmanjunath** [comment]
Thanks for the suggestion @superoo7. We considered that approach too, but as far as I'm aware, indexed db is open to the same vulnerability as localStorage. While chrome extensions and requests from third party domains still can't access indexed db, any javascript imported through the <script> tag can still access to the local domain's indexed db.
